---
- hosts: all
  tasks:
    - name: Install apt dependencies
      apt:
        name:
          - sudo
          - xserver-xorg-core
          - xvfb
          - flatpak
          - python3-pip
          - python3-tk
          - xdotool
          - x11vnc
        update_cache: yes
        state: present

    - name: Create discord user
      user:
        name: discord
        create_home: yes
        shell: /bin/bash

    - name: Create Discord Flatpak config dir
      file:
        path: "/home/discord/.var/app/com.discordapp.Discord/config/discord/Local Storage"
        state: directory
        mode: '0755'
        owner: discord
        group: discord

    # idk if you need to whole leveldb dir or maybe a single sqlite file?
    - name: Copy Discord config
      copy:
        src: leveldb
        dest: "/home/discord/.var/app/com.discordapp.Discord/config/discord/Local Storage"
        owner: discord
        group: discord

    - name: Enable Flathub repository
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
        method: user
      become: yes
      become_user: discord

    - name: Install Discord
      flatpak:
        name: com.discordapp.Discord
        state: present
        method: user
      become: yes
      become_user: discord

    - name: Copy discord script
      copy:
        src: discord.sh
        dest: /usr/local/bin/discord.sh
        mode: '0755'
        owner: root
        group: root
    
    - name: Create systemd user dir
      file:
        path: /home/discord/.config/systemd/user
        state: directory
        mode: '0755'
        owner: discord
        group: discord

    - name: Template discord systemd service
      template:
        src: discord.service.j2
        dest: /home/discord/.config/systemd/user/discord.service
        mode: '0644'
        owner: discord
        group: discord

    - name: Allow discord user services to run on boot
      command: loginctl enable-linger discord

    - name: Start and enable discord service
      systemd:
        daemon_reload: yes
        name: discord.service
        state: restarted
        enabled: yes
        scope: user
      become: yes
      become_user: discord
